# ???? ?? ????? ?? application.properties ?????? ???? Docker
# ????? ?????? ??????? ?-docker-compose.yml

server.port=8080
spring.application.name=fraud-backend-server

# URL ????? ?? ?? ?-service ?? PostgreSQL ?-docker-compose (?? localhost)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false

application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}
application.security.jwt.expiration=${APPLICATION_SECURITY_JWT_EXPIRATION:86400000}

# URL ?? ??? ?????? ???? ??? ?-Docker
victim.url=${VICTIM_URL:http://victim-server:8081}
